title: Pyrrhamide
author: KF
email: email@domain.com
description: >
   "I'll keep all my plans close to my chest.
   I'll wait here and see which way the wind will blow. 
   I'm taking my time watching the afterbirth of our nation, 
   Watching the tension grooooow."

github_username: pyrrhamide

show_excerpts: true

theme: minima

favicon: favicon.ico